const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const memoryStore={};
const store={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??memoryStore[k]??d}catch{return memoryStore[k]??d}},set:(k,v)=>{memoryStore[k]=v;try{localStorage.setItem(k,JSON.stringify(v))}catch{}}};
let currentReadiness=78, voiceOn=false;
const events=['55m','60m','100m','200m','300m','400m','800m','1600m','3200m','5K','100m Hurdles','110m Hurdles','300m Hurdles','400m Hurdles','Long Jump','Triple Jump','High Jump','Pole Vault','Shot Put','Discus','Javelin','Multi-Event'];
const groups={sprint:['55m','60m','100m','200m','300m','400m'],endurance:['800m','1600m','3200m','5K'],hurdle:['100m Hurdles','110m Hurdles','300m Hurdles','400m Hurdles'],jump:['Long Jump','Triple Jump','High Jump','Pole Vault'],throw:['Shot Put','Discus','Javelin'],multi:['Multi-Event']};
const getGroup=e=>Object.entries(groups).find(([,a])=>a.includes(e))?.[0]||'sprint';
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function speak(text){if(!('speechSynthesis'in window))return toast('Voice summaries are not supported in this browser');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.98;u.pitch=1.02;speechSynthesis.speak(u)}

// Profile
$$('.event-select').forEach((s,i)=>{s.innerHTML=events.map(e=>`<option ${i===0&&e==='400m'?'selected':''}>${e}</option>`).join('')});
function loadProfile(){const p=store.get('athena_os_profile',null);if(!p)return;Object.entries(p).forEach(([k,v])=>{const el=$('#'+k);if(el)el.value=v});updateReadiness()}
$('#saveProfile').onclick=()=>{const p={athleteName:$('#athleteName').value,athleteAge:$('#athleteAge').value,athleteLevel:$('#athleteLevel').value,primaryEvent:$('#primaryEvent').value,secondaryEvent:$('#secondaryEvent').value,baselineHr:$('#baselineHr').value};store.set('athena_os_profile',p);$('#handoffName').value=p.athleteName;toast('Athlete profile saved on this device');updateReadiness()};

// Readiness
const rids=['sleep','energy','soreness','stress','hydration','restingHr','load','healthFlag','primaryEvent','baselineHr'];
rids.forEach(id=>$('#'+id)?.addEventListener('input',updateReadiness));
function updateReadiness(){
 const sleep=+$('#sleep').value, energy=+$('#energy').value, sore=+$('#soreness').value, stress=+$('#stress').value, hyd=+$('#hydration').value, hr=+$('#restingHr').value, load=+$('#load').value, flag=$('#healthFlag').value, base=+$('#baselineHr').value||68, event=$('#primaryEvent').value, group=getGroup(event);
 $('#sleepOut').value=`${sleep.toFixed(1)} h`;$('#energyOut').value=`${energy} / 10`;$('#sorenessOut').value=`${sore} / 10`;$('#stressOut').value=`${stress} / 10`;$('#loadOut').value=`${load} / 10`;$('#eventBias').textContent=`${group[0].toUpperCase()+group.slice(1)} profile`;
 const weights={sprint:{sleep:.19,energy:.22,sore:.22,stress:.1,hyd:.12,hr:.08,load:.07},endurance:{sleep:.21,energy:.17,sore:.13,stress:.09,hyd:.2,hr:.12,load:.08},hurdle:{sleep:.18,energy:.2,sore:.23,stress:.1,hyd:.11,hr:.08,load:.1},jump:{sleep:.17,energy:.2,sore:.25,stress:.1,hyd:.1,hr:.06,load:.12},throw:{sleep:.16,energy:.2,sore:.25,stress:.12,hyd:.1,hr:.05,load:.12},multi:{sleep:.2,energy:.18,sore:.2,stress:.1,hyd:.13,hr:.09,load:.1}}[group];
 const signals={sleep:Math.min(100,Math.max(0,(sleep-4)/4*100)),energy:energy*10,sore:(10-sore)*10,stress:(10-stress)*10,hyd,hr:Math.max(0,100-Math.max(0,hr-base)*7),load:Math.max(0,100-Math.max(0,load-4)*10)};
 let score=Math.round(Object.keys(weights).reduce((a,k)=>a+signals[k]*weights[k],0));
 if(flag==='pain')score=Math.min(score,46);if(flag==='illness')score=Math.min(score,35);if(flag==='breathing'||flag==='head')score=Math.min(score,15);
 score=Math.max(5,Math.min(100,score));currentReadiness=score;
 let label='RECOVER',summary='Several signals suggest stopping hard training and speaking with a trusted adult, coach, nurse, athletic trainer, or clinician.',fit='Recovery / professional check-in';
 if(score>=85){label='PRIMED';summary=`Your ${event} profile and today’s signals support a high-quality session, while still requiring a full warm-up and symptom awareness.`;fit=group==='endurance'?'Quality aerobic or race-specific work':group==='throw'?'Technical throws + strength quality':group==='jump'?'Approach rhythm + high-quality jumps':group==='hurdle'?'Rhythm + controlled speed':'Speed / technical quality'}
 else if(score>=68){label='READY';summary='A normal session may fit. Preserve quality, watch the first few reps, and adjust volume if your body feels worse than the numbers suggest.';fit='Controlled quality'}
 else if(score>=50){label='CAUTION';summary='Your signals are mixed. Favor technique, lower volume, or lower intensity and address the biggest limiting factor first.';fit='Technique / reduced load'}
 else if(score>=25){label='RECOVER';summary='Today’s data does not support a hard session. Choose recovery and tell a trusted adult about pain, illness, or worsening symptoms.';fit='Recovery / reassessment'}
 if(flag==='breathing'||flag==='head')summary='Stop activity and tell an adult immediately. A breathing concern or possible concussion needs prompt evaluation; emergency warning signs require 911.';
 $('#readinessScore').textContent=score;$('#readinessLabel').textContent=label;$('#readinessRing').style.setProperty('--score',score);$('#readinessSummary').textContent=summary;$('#bestFit b').textContent=fit;
 const factors=[['Sleep',Math.round(signals.sleep),sleep>=8?`${sleep.toFixed(1)}h supports recovery`:`${sleep.toFixed(1)}h is below the teen 8h floor`],['Energy',signals.energy,`${energy}/10 self-report`],['Muscle state',signals.sore,`${sore}/10 soreness`],['Hydration',signals.hyd,hyd>=78?'On track':'Needs attention']];
 $('#factorGrid').innerHTML=factors.map(([n,v,d])=>`<div class="factor ${v<60?'negative':''}"><small>${n} · ${v}%</small><b>${d}</b></div>`).join('');
 const rec=[];if(sleep<8)rec.push('Protect 8–10 hours tonight');if(energy<5)rec.push('Lower session demand');if(sore>=6)rec.push('Report pain or unusual soreness');if(stress>=7)rec.push('Simplify today’s plan');if(hyd<70)rec.push('Rehydrate before hard work');if(hr-base>=8)rec.push('Resting pulse is above baseline');if(load>=8)rec.push('Avoid stacking maximal days');if(flag!=='none')rec.push('Health flag overrides performance goals');if(!rec.length)rec.push('Maintain normal recovery habits');
 $('#recommendations').innerHTML=rec.map(x=>`<span>${x}</span>`).join('');updateCompatibility();return {score,label,summary,fit,event,group}
}
$('#saveCheckin').onclick=()=>{const r=updateReadiness(),d=store.get('athena_os_checkins',[]);d.push({date:new Date().toISOString(),label:new Date().toLocaleDateString(undefined,{weekday:'short'}),score:r.score,event:r.event});store.set('athena_os_checkins',d.slice(-60));drawTrend();toast('Check-in saved locally')};
$('#speakSummary').onclick=()=>{const r=updateReadiness();speak(`ATHENA readiness ${r.score}, ${r.label}. ${r.summary} Best fit session: ${r.fit}.`)};
$('#voiceToggle').onclick=()=>{voiceOn=!voiceOn;$('#voiceToggle').textContent=voiceOn?'◉':'◖';toast(`Voice summaries ${voiceOn?'on':'off'}`)};

// session compatibility
['plannedSession','sessionIntensity','sessionDuration','sessionTemp'].forEach(id=>$('#'+id).addEventListener('input',updateCompatibility));
function updateCompatibility(){if(!$('#sessionIntensity'))return;const inten=+$('#sessionIntensity').value,dur=+$('#sessionDuration').value,temp=+$('#sessionTemp').value,type=$('#plannedSession').value;$('#intensityOut').value=`${inten} / 10`;let score=currentReadiness-(inten-5)*4-Math.max(0,dur-90)*.12-Math.max(0,temp-82)*.8;const group=getGroup($('#primaryEvent').value);const match={sprint:['speed','speedend','strength'],endurance:['tempo','distance','recovery'],hurdle:['hurdles','speed','strength'],jump:['jumps','speed','strength'],throw:['throws','strength'],multi:['speed','hurdles','jumps','throws','strength']}[group];if(match.includes(type))score+=6;if(type==='recovery')score+=16;if($('#healthFlag').value!=='none'&&type!=='recovery')score-=25;score=Math.max(5,Math.min(98,Math.round(score)));$('#compatibilityScore').textContent=`${score}%`;$('#compatibilityFill').style.width=`${score}%`;let label='Not a good fit',text='Choose recovery and discuss concerning symptoms with a trusted adult.';if(score>=82){label='Strong fit';text='The planned session aligns with today’s signals. Keep quality high and stop if symptoms change.'}else if(score>=64){label='Compatible with adjustments';text='Keep the main goal, but reduce total volume or extend recovery if quality falls.'}else if(score>=45){label='Low compatibility';text='Convert the session toward technique, lower intensity, or shorter duration.'}$('#compatibilityLabel').textContent=label;$('#compatibilityText').textContent=text;const a=[];if(inten>=8&&currentReadiness<75)a.push('Cap maximal reps');if(dur>90)a.push('Shorten total duration');if(temp>=85)a.push('Add heat precautions');if(!match.includes(type)&&type!=='recovery')a.push(`Not primary for ${group} profile`);if($('#healthFlag').value!=='none')a.push('Health concern comes before session');if(!a.length)a.push('No major adjustment identified');$('#sessionAdjustments').innerHTML=a.map(x=>`<span>${x}</span>`).join('')}

// Charts
function drawLine(canvas,data,colorVar='--accent'){const c=$(canvas),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);if(!data.length)return false;const vals=data.map(d=>d.value),min=Math.min(...vals),max=Math.max(...vals),range=Math.max(1,max-min);ctx.strokeStyle=getComputedStyle(document.body).getPropertyValue('--line');ctx.lineWidth=1;[.2,.5,.8].forEach(f=>{const y=20+(h-50)*f;ctx.beginPath();ctx.moveTo(25,y);ctx.lineTo(w-15,y);ctx.stroke()});const pts=data.map((d,i)=>({x:25+i*((w-50)/Math.max(1,data.length-1)),y:20+(max-d.value)/range*(h-55)}));ctx.strokeStyle=getComputedStyle(document.body).getPropertyValue(colorVar);ctx.lineWidth=5;ctx.lineJoin='round';ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();pts.forEach(p=>{ctx.fillStyle=getComputedStyle(document.body).getPropertyValue(colorVar);ctx.beginPath();ctx.arc(p.x,p.y,5,0,Math.PI*2);ctx.fill()});return true}
function drawTrend(){const d=store.get('athena_os_checkins',[]).slice(-10).map(x=>({value:x.score}));$('#chartEmpty').style.display=drawLine('#trendChart',d)?'none':'block'}
$('#clearHistory').onclick=()=>{localStorage.removeItem('athena_os_checkins');drawTrend();toast('Readiness history reset')};

// Event tabs
$$('.event-tab').forEach(b=>b.onclick=()=>{$$('.event-tab').forEach(x=>x.classList.remove('active'));$$('.event-pane').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#pane-'+b.dataset.tab).classList.add('active')});
function fmt(sec){const m=Math.floor(sec/60),s=(sec-m*60).toFixed(2).padStart(5,'0');return m?`${m}:${s}`:`${s}s`}
function parseTime(v){const p=String(v).split(':').map(Number);if(p.some(Number.isNaN))return 0;return p.length===1?p[0]:p.length===2?p[0]*60+p[1]:p[0]*3600+p[1]*60+p[2]}
function phaseHTML(title,total,phases){return `<div class="blueprint-title"><div><small>PROJECTED RESULT</small><h3>${title}</h3></div><strong>${fmt(total)}</strong></div><div class="phase-list">${phases.map(p=>`<div class="phase"><b>${p.name}</b><div><div class="phase-bar"><span style="width:${p.pct}%"></span></div><small>${p.cue}</small></div><strong>${fmt(p.time)}</strong></div>`).join('')}</div>`}
function sprintPlan(){const dist=+$('#sprintEvent').value,t=+$('#sprintGoal').value||13.2,str=$('#sprintStrength').value;let defs;if(dist<=100)defs=[['Drive',.30,'Push, rise gradually'],['Transition',.27,'Blend into upright sprinting'],['Max velocity',.27,'Relaxed speed'],['Finish',.16,'Hold mechanics through line']];else if(dist===200)defs=[['Curve attack',.48,'Build speed without forcing'],['Straight transition',.18,'Stay tall and relaxed'],['Finish',.34,'Protect posture under fatigue']];else if(dist===300)defs=[['Controlled launch',.33,'Fast but sustainable'],['Backstretch rhythm',.31,'Float without switching off'],['Finish pressure',.36,'Arms and posture late']];else defs=[['First 100',.235,'Controlled aggression'],['Second 100',.245,'Settle into rhythm'],['Third 100',.255,'Commit on the curve'],['Final 100',.265,'Maintain form under fatigue']];if(str==='start'){defs[0][1]-=.02;defs[defs.length-1][1]+=.02}if(str==='finish'){defs[0][1]+=.02;defs[defs.length-1][1]-=.02}const sum=defs.reduce((a,x)=>a+x[1],0);$('#sprintBlueprint').innerHTML=phaseHTML(`${dist}m blueprint`,t,defs.map(x=>({name:x[0],time:t*x[1]/sum,pct:x[1]/sum*100,cue:x[2]})))}
$('#buildSprintPlan').onclick=sprintPlan;['sprintEvent','sprintGoal','sprintStrength'].forEach(id=>$('#'+id).oninput=sprintPlan);
function hurdlePlan(){const e=$('#hurdleEvent').value,t=+$('#hurdleGoal').value||18.5,a=+$('#hurdleAllowance').value||4.5;const count={'100h':10,'110h':10,'300h':8,'400h':10}[e],rhythm=(t-a)/Math.max(1,count-1);$('#hurdleBlueprint').innerHTML=`<div class="blueprint-title"><div><small>RHYTHM MODEL</small><h3>${e.toUpperCase()}</h3></div><strong>${fmt(t)}</strong></div><div class="metric-grid"><div><small>Hurdles</small><b>${count}</b></div><div><small>Average between hurdles</small><b>${rhythm.toFixed(2)}s</b></div><div><small>Start + finish allowance</small><b>${a.toFixed(1)}s</b></div></div><div class="medical-note">Use this as a planning estimate. Actual rhythm varies across the race, especially in 300m and 400m hurdles.</div>`}
$('#buildHurdlePlan').onclick=hurdlePlan;['hurdleEvent','hurdleGoal','hurdleAllowance'].forEach(id=>$('#'+id).oninput=hurdlePlan);
function distancePlan(){const dist=+$('#distanceEvent').value,t=parseTime($('#distanceGoal').value)||345,str=$('#distanceStrategy').value;let adj=[1,1,1,1];if(str==='negative')adj=[1.02,1.01,.99,.98];if(str==='aggressive')adj=[.97,.99,1.01,1.03];const splits=[200,400,800,1000].filter(x=>x<=dist);const rows=splits.map(d=>{let base=t*d/dist;return `<div class="phase"><b>${d===1000?'1 km':d+'m'}</b><div><div class="phase-bar"><span style="width:${Math.min(100,d/dist*100)}%"></span></div><small>${str.replace(/^./,c=>c.toUpperCase())} strategy</small></div><strong>${fmt(base)}</strong></div>`}).join('');const laps=Math.ceil(dist/400),lapBase=t/laps;const lapRows=Array.from({length:laps},(_,i)=>{const mult=adj[Math.min(3,Math.floor(i/laps*4))];return `<span>Lap ${i+1}<b>${fmt(lapBase*mult)}</b></span>`}).join('');$('#distanceBlueprint').innerHTML=`<div class="blueprint-title"><div><small>GOAL PACE</small><h3>${dist===5000?'5K':dist+'m'} matrix</h3></div><strong>${fmt(t)}</strong></div><div class="phase-list">${rows}</div><div class="recommendations">${lapRows}</div>`}
$('#buildPacePlan').onclick=distancePlan;['distanceEvent','distanceGoal','distanceStrategy'].forEach(id=>$('#'+id).oninput=distancePlan);

// attempts
function attemptModule(kind){const key=`athena_${kind}_attempts`,mark=$(`#${kind}Mark`),foul=$(`#${kind}Foul`),series=$(`#${kind}Series`),stats=$(`#${kind}Stats`);function render(){const a=store.get(key,[]),legal=a.filter(x=>!x.foul);series.innerHTML=a.length?a.map((x,i)=>`<div class="attempt ${x.foul?'foul':''}"><small>#${i+1}</small><b>${x.foul?'FOUL':x.mark.toFixed(2)+'m'}</b></div>`).join(''):'<p class="muted">No attempts recorded.</p>';const vals=legal.map(x=>x.mark),best=vals.length?Math.max(...vals):0,avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0,spread=vals.length>1?Math.max(...vals)-Math.min(...vals):0;stats.innerHTML=`<div><small>Best</small><b>${best?best.toFixed(2)+'m':'—'}</b></div><div><small>Legal average</small><b>${avg?avg.toFixed(2)+'m':'—'}</b></div><div><small>Consistency spread</small><b>${spread?spread.toFixed(2)+'m':'—'}</b></div>`} $(`#add${kind[0].toUpperCase()+kind.slice(1)}`).onclick=()=>{const v=+mark.value;if(!v&&!foul.checked)return toast('Enter a mark or choose foul');const a=store.get(key,[]);a.push({mark:v||0,foul:foul.checked});store.set(key,a);mark.value='';foul.checked=false;render()};$(`#reset${kind[0].toUpperCase()+kind.slice(1)}s`).onclick=()=>{localStorage.removeItem(key);render()};render()}
attemptModule('jump');attemptModule('throw');

// relay optimizer
const defaultAthletes=[['Athlete A',64.2,8,7,9,8],['Athlete B',63.8,7,8,7,7],['Athlete C',65.0,9,6,8,9],['Athlete D',62.9,6,9,9,8]];
function renderRelayAthletes(){const box=$('#relayAthletes');box.innerHTML=defaultAthletes.map((a,i)=>`<div class="relay-athlete"><h4>Athlete ${i+1}</h4><input class="ra-name" value="${a[0]}" aria-label="Athlete ${i+1} name"><div class="mini-fields"><label>Time<input class="ra-time" type="number" step=".01" value="${a[1]}"></label><label>Curve<input class="ra-curve" type="number" min="1" max="10" value="${a[2]}"></label><label>Exchange<input class="ra-exchange" type="number" min="1" max="10" value="${a[3]}"></label><label>Finish<input class="ra-finish" type="number" min="1" max="10" value="${a[4]}"></label><label>Pressure<input class="ra-pressure" type="number" min="1" max="10" value="${a[5]}"></label></div></div>`).join('')}
function perms(a){if(a.length<2)return[a];return a.flatMap((x,i)=>perms([...a.slice(0,i),...a.slice(i+1)]).map(p=>[x,...p]))}
function optimizeRelay(){const type=$('#relayEvent').value,names=$$('.ra-name').map(x=>x.value||'Athlete'),data=names.map((name,i)=>({name,time:+$$('.ra-time')[i].value,curve:+$$('.ra-curve')[i].value,exchange:+$$('.ra-exchange')[i].value,finish:+$$('.ra-finish')[i].value,pressure:+$$('.ra-pressure')[i].value}));const results=perms([0,1,2,3]).map(order=>{let total=0,why=[];order.forEach((idx,leg)=>{const a=data[idx];let penalty=0;if(type==='4x100'||type==='4x200'){penalty+=(10-a.exchange)*.035;if(leg===0||leg===2)penalty+=(10-a.curve)*.025}else if(type==='4x400'){if(leg===0)penalty+=(10-a.curve)*.03;if(leg===3)penalty+=(10-a.finish)*.04+(10-a.pressure)*.025}else{if(leg===0)penalty+=(10-a.pressure)*.05;if(leg===3)penalty+=(10-a.finish)*.07}total+=a.time+penalty});const anchor=data[order[3]];why.push(`Anchor: ${anchor.name} (${anchor.finish}/10 finish, ${anchor.pressure}/10 pressure)`);if(type==='4x100'||type==='4x200')why.push('Exchange and curve ratings influence placement');else why.push('Leg demands influence the planning score');return{order,total,why}}).sort((a,b)=>a.total-b.total).slice(0,3);$('#relayResults').innerHTML=results.map((r,i)=>`<article class="relay-card"><span class="rank">#${i+1} MODEL</span><h3>${fmt(r.total)}</h3><div class="relay-order">${r.order.map((idx,leg)=>`<span>L${leg+1}: ${data[idx].name}</span>`).join('')}</div><p class="muted">${r.why.join('. ')}.</p></article>`).join('')}
renderRelayAthletes();$('#optimizeRelay').onclick=optimizeRelay;optimizeRelay();

// Health
function heatCalc(){const t=+$('#heatTemp').value,h=+$('#heatHumidity').value,d=+$('#heatDuration').value,int=+$('#heatIntensity').value,acc=+$('#heatAcclimated').value,dem=+$('#heatEventDemand').value;let burden=(t-70)*1.4+h*.16+d*.08+int*8+dem*5+(acc?0:12);let level='Standard awareness',cls='',advice=['Have water available','Use gradual pacing','Monitor symptoms'];if(burden>100){level='High concern — involve athletic staff';cls='danger';advice=['Modify, move, or postpone hard work','Increase cooling and rest access','Follow school heat policy / official WBGT','Stop immediately for confusion, collapse, or worsening symptoms']}else if(burden>75){level='Extra precautions recommended';cls='warn';advice=['Add scheduled breaks','Use shade or cooling','Reduce volume or intensity','Watch for headache, dizziness, nausea, weakness, or cramps']}const el=$('#heatResult');el.className=`health-result ${cls}`;el.innerHTML=`<small>EDUCATIONAL AWARENESS LEVEL</small><h3>${level}</h3><div class="recommendations">${advice.map(x=>`<span>${x}</span>`).join('')}</div><p class="fine-print">This is not WBGT and does not replace your school, coach, athletic trainer, nurse, or local policy.</p>`}
['heatTemp','heatHumidity','heatDuration','heatIntensity','heatAcclimated','heatEventDemand'].forEach(id=>$('#'+id).oninput=heatCalc);
function heartCalc(){const age=+$('#heartAge').value||15,max=220-age;$('#maxHr').textContent=`${max} bpm`;$('#moderateHr').textContent=`${Math.round(max*.5)}–${Math.round(max*.7)}`;$('#vigorousHr').textContent=`${Math.round(max*.7)}–${Math.round(max*.85)}`}
$('#heartAge').oninput=heartCalc;
const days=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
function sleepRender(){const vals=store.get('athena_sleep_week',[8,8,8,8,8,8.5,8.5]);$('#sleepWeek').innerHTML=days.map((d,i)=>`<label class="sleep-day"><small>${d}</small><input class="sleep-hour" type="number" min="0" max="14" step=".1" value="${vals[i]}"></label>`).join('');$$('.sleep-hour').forEach((e,i)=>e.oninput=()=>{const a=$$('.sleep-hour').map(x=>+x.value||0);store.set('athena_sleep_week',a);sleepSummary(a)});sleepSummary(vals)}
function sleepSummary(a){const avg=a.reduce((x,y)=>x+y,0)/7,under=a.filter(x=>x<8).length,el=$('#sleepSummary');let cls='',title='Strong recovery pattern',msg='Your seven-night average is within the general 8–10 hour range for teens.';if(avg<8){cls='warn';title='Recovery opportunity';msg=`${under} night(s) were below 8 hours. Protecting a consistent schedule may support learning, reaction, and recovery.`}if(avg<6.5){cls='danger';title='Significant sleep concern';msg='Your average is far below general teen guidance. Tell a parent or healthcare professional if sleep problems persist.'}el.className=`health-result ${cls}`;el.innerHTML=`<small>7-NIGHT AVERAGE</small><h3>${avg.toFixed(1)} hours</h3><b>${title}</b><p>${msg}</p>`}
$('#resetSleep').onclick=()=>{localStorage.removeItem('athena_sleep_week');sleepRender()};
const concerns={heat:{title:'Possible heat illness',steps:['Stop activity and move to a cooler place.','Tell a coach, nurse, athletic trainer, parent, or other trusted adult immediately.','Do not wait for symptoms to become severe.'],urgent:'Confusion, collapse, fainting, seizure, or very hot skin can signal an emergency. Call 911 and begin rapid cooling while help is coming.'},head:{title:'Possible concussion after a hit',steps:['Leave activity immediately.','Tell an adult and do not return the same day without appropriate evaluation and clearance.','Continue monitoring because symptoms can appear later.'],urgent:'Call 911 for repeated vomiting, worsening headache, seizure, slurred speech, increasing confusion, unequal pupils, severe drowsiness, weakness, or loss of consciousness.'},breathing:{title:'Breathing concern',steps:['Stop activity and sit upright in a safe place.','Tell an adult immediately and follow an existing asthma or emergency action plan.','Do not borrow another person’s medication.'],urgent:'Call 911 for severe breathing difficulty, blue or gray lips, fainting, inability to speak normally, or rapidly worsening symptoms.'},cardiac:{title:'Chest pain, fainting, or unusual heart symptoms',steps:['Stop activity immediately.','Tell an adult and seek prompt medical evaluation.','Do not “push through” chest pain, fainting, or near-fainting.'],urgent:'Call 911 for collapse, unresponsiveness, severe chest pain, or abnormal breathing. Begin CPR and use an AED if trained and available.'},injury:{title:'Serious injury',steps:['Stop activity and avoid unnecessary movement.','Tell a coach, nurse, athletic trainer, or parent.','Do not force weight-bearing on a severely painful or deformed limb.'],urgent:'Call 911 for suspected neck/spine injury, uncontrolled bleeding, exposed bone, loss of feeling, severe deformity, or any life-threatening concern.'}};
function showConcern(k){const c=concerns[k];$('#concernContent').innerHTML=`<h3>${c.title}</h3><ul>${c.steps.map(x=>`<li>${x}</li>`).join('')}</ul><div class="urgent"><b>Emergency warning:</b> ${c.urgent}</div>`}
$$('.concern').forEach(b=>b.onclick=()=>{$$('.concern').forEach(x=>x.classList.remove('active'));b.classList.add('active');showConcern(b.dataset.concern)});

// Handoff
const symptoms=['Headache','Dizziness','Nausea','Weakness','Cramping','Shortness of breath','Chest pain','Vision change','Numbness / tingling','Swelling','Bleeding','Confusion'];
$('#symptomGrid').innerHTML=symptoms.map(s=>`<label class="symptom-option"><input type="checkbox" value="${s}"> ${s}</label>`).join('');
$('#handoffPain').oninput=()=>$('#painOut').value=`${$('#handoffPain').value} / 10`;
function buildHandoff(e){e?.preventDefault();const name=$('#handoffName').value||'The athlete',sym=$$('#symptomGrid input:checked').map(x=>x.value),status=$('#handoffStatus').value,red=['Confused or acting unusually','Breathing is difficult','Fainted / lost consciousness','Repeated vomiting'].includes(status)||sym.includes('Chest pain');const note=`<h4>S — Situation</h4><p><b>${name}</b> was participating in <b>${$('#handoffEvent').value||'track and field activity'}</b>. ${$('#handoffSituation').value}. Symptoms began ${$('#handoffOnset').value||'at an unspecified time'}.</p><h4>B — Background</h4><p>${$('#handoffBackground').value||'No additional background was entered.'}</p><h4>A — Athlete-reported assessment</h4><p>Current status: <b>${status}</b>. Pain/discomfort: <b>${$('#handoffPain').value}/10</b>. Reported symptoms: <b>${sym.length?sym.join(', '):'none selected'}</b>.</p><p>Actions already taken: ${$('#handoffActions').value||'none entered'}.</p><h4>R — Request</h4><p><b>${$('#handoffRequest').value}</b>. Please assess the athlete and determine appropriate next steps. This note is athlete-reported and is not a diagnosis.</p>`;$('#handoffNote').innerHTML=note;$('#urgentBanner').classList.toggle('hidden',!red);$('#urgentBanner').textContent=red?'URGENT WARNING: Stop activity and get immediate adult help. Call 911 for severe or worsening symptoms, collapse, unresponsiveness, severe breathing difficulty, or chest pain.':'';if(voiceOn)speak(`${name} handoff created. ${red?'Urgent warning detected. Get immediate adult help.':''}`)}
$('#handoffForm').onsubmit=buildHandoff;$('#copyHandoff').onclick=async()=>{await navigator.clipboard.writeText($('#handoffNote').innerText);toast('Handoff copied')};$('#printHandoff').onclick=()=>window.print();

// Research
function renderProtocol(){const p=store.get('athena_research_protocol',null),card=$('#protocolCard');if(!p){card.className='protocol-card empty-state';card.textContent='Create a protocol to begin.'}else{card.className='protocol-card';card.innerHTML=`<small>ACTIVE PROTOCOL · ${p.days} DAYS</small><h4>${p.question}</h4><p><b>Change:</b> ${p.iv}<br><b>Measure:</b> ${p.metric}<br><b>Plan:</b> ${p.plan||'Not specified'}<br><b>Safety:</b> ${p.safety}</p>`}renderObservations()}
$('#researchForm').onsubmit=e=>{e.preventDefault();store.set('athena_research_protocol',{question:$('#researchQuestion').value,iv:$('#researchIV').value,metric:$('#researchMetric').value,days:$('#researchDays').value,safety:$('#researchSafety').value,plan:$('#researchPlan').value});renderProtocol();toast('Research protocol saved locally')};
$('#observationDate').valueAsDate=new Date();$('#observationForm').onsubmit=e=>{e.preventDefault();const a=store.get('athena_research_obs',[]);a.push({date:$('#observationDate').value,value:+$('#observationValue').value,note:$('#observationNote').value});store.set('athena_research_obs',a);e.target.reset();$('#observationDate').valueAsDate=new Date();renderObservations()};
function renderObservations(){const a=store.get('athena_research_obs',[]);$('#observationList').innerHTML=a.slice().reverse().map((x,ri)=>{const i=a.length-1-ri;return `<div class="observation"><span>${x.date}</span><b>${x.value}</b><span>${x.note||'—'}</span><button class="text-btn" data-obs="${i}">×</button></div>`}).join('');$$('[data-obs]').forEach(b=>b.onclick=()=>{const x=store.get('athena_research_obs',[]);x.splice(+b.dataset.obs,1);store.set('athena_research_obs',x);renderObservations()});drawLine('#researchChart',a.map(x=>({value:x.value})),'--accent2')}
$('#exportResearch').onclick=()=>{const p=store.get('athena_research_protocol',{}),a=store.get('athena_research_obs',[]),csv=['date,value,note',...a.map(x=>`${x.date},${x.value},"${(x.note||'').replaceAll('"','""')}"`)].join('\n'),blob=new Blob([csv],{type:'text/csv'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='athena-research-data.csv';link.click();URL.revokeObjectURL(link.href);toast('Research data exported')};

// Resume copy
const resumeText=`ATHENA OS — Athlete Health Intelligence Platform | Co-Founder & Co-Lead Developer (50/50 collaboration)
• Co-created a privacy-first web platform supporting sprinters, hurdlers, distance runners, jumpers, throwers, and relay teams through event-specific performance tools and explainable readiness insights.
• Jointly engineered a relay optimizer that evaluates all 24 possible four-athlete orders using performance times and leg-specific curve, exchange, endurance, and pressure ratings.
• Built an SBAR-style athlete-to-nurse handoff system that converts symptoms, context, and actions into clear communication while escalating emergency warning signs.
• Developed interactive sprint, hurdle, distance, jump, throw, heat-awareness, heart-rate education, sleep-pattern, and athlete research modules using JavaScript and privacy-preserving local storage.
• Shared equal responsibility for product strategy, research, UX/UI design, front-end development, testing, documentation, accessibility, offline functionality, and responsible health-safety framing.
Co-Founders: Nikitha Mallojhala (nikitha.mallojhala@gmail.com) and Shriyan Avadhanula (avadhanula.shriyan@gmail.com).`;
$('#copyResume').onclick=async()=>{await navigator.clipboard.writeText(resumeText);toast('Resume bullets copied')};

// theme/offline/reveal
$('#themeToggle').onclick=()=>{document.body.classList.toggle('light');store.set('athena_os_theme',document.body.classList.contains('light')?'light':'dark');drawTrend();renderObservations()};if(store.get('athena_os_theme','dark')==='light')document.body.classList.add('light');
const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.06});$$('.reveal').forEach(x=>obs.observe(x));
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});

// init
loadProfile();updateReadiness();drawTrend();sprintPlan();hurdlePlan();distancePlan();heatCalc();heartCalc();sleepRender();showConcern('heat');renderProtocol();buildHandoff();
